baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = "PaperMod"

[params.profileMode]
    enabled = false
    title = "이종완 (Jongwan Lee)"
    subtitle = "공식 문서와 논리를 바탕으로 견고한 제품을 만드는 10년 차 엔지니어입니다."
    imageUrl = "본인_사진_경로" # 생략 가능
    imageTitle = "Jongwan"

    [[params.profileMode.buttons]]
        name = "Projects"
        url = "/posts" # 글 목록으로 연결

    [[params.profileMode.buttons]]
        name = "GitHub"
        url = "https://github.com/본인아이디"
